(()=>{
'use strict';
const modal=document.querySelector('#pandal-details');
const nav=document.querySelector('.site-header nav');
const menu=document.querySelector('.site-header .menu');
if(nav&&menu){
 const style=document.createElement('style');style.textContent=`@media(max-width:800px){.site-header .menu{display:flex!important;align-items:center;justify-content:center;width:44px;height:44px;padding:10px;margin:0;cursor:pointer;z-index:1001;touch-action:manipulation}.site-header .menu span{pointer-events:none;transition:transform .18s ease,opacity .18s ease}.site-header .menu[aria-expanded="true"] span:first-child{transform:translateY(3.5px) rotate(45deg)}.site-header .menu[aria-expanded="true"] span:last-child{transform:translateY(-3.5px) rotate(-45deg)}.site-header nav{display:none!important;position:absolute;top:72px;right:16px;z-index:1000;min-width:190px;flex-direction:column;align-items:stretch;gap:2px;padding:8px;background:rgba(247,244,238,.98);border:1px solid var(--line);border-radius:14px;box-shadow:0 12px 32px rgba(24,21,18,.14)}.site-header nav[data-open="true"]{display:flex!important}.site-header nav a{display:block;padding:13px 14px;opacity:1!important;color:var(--ink)!important;border-radius:9px}.site-header nav a::after{display:none}}@media(min-width:801px){.site-header nav{display:flex!important}.site-header .menu{display:none!important}}`;document.head.appendChild(style);
 const setOpen=open=>{nav.dataset.open=String(open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')};
 menu.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setOpen(nav.dataset.open!=='true')});
 nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=800)setOpen(false)}));
 document.addEventListener('click',e=>{if(innerWidth<=800&&nav.dataset.open==='true'&&!nav.contains(e.target)&&!menu.contains(e.target))setOpen(false)});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&innerWidth<=800&&nav.dataset.open==='true'){e.preventDefault();setOpen(false);menu.focus()}});
 const sync=()=>{if(innerWidth>800)setOpen(false)};addEventListener('resize',sync,{passive:true});sync();
}
if(!modal)return;
const $=s=>modal.querySelector(s);const find=name=>window.pandals?.find?.(p=>p.name===name)||null;let current=null,lastFocus=null;
const mode=()=>{const m=window.KolkataState?.get?.().mode||document.querySelector('.mode-btn.active')?.dataset.mode||'walking';return m==='two-wheeler'?'driving':m};
const maps=p=>{if(!p)return 'https://www.google.com/maps/search/?api=1&query=Kolkata%20Durga%20Puja';if(Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng)))return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${p.lat},${p.lng}`)}&travelmode=${encodeURIComponent(mode())}`;return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name}, ${p.area||''}, Kolkata, West Bengal`)}`};
function openDetails(name){const p=find(name);if(!p)return;current=p;lastFocus=document.activeElement;const img=$('#details-image');if(img){img.onerror=()=>{img.removeAttribute('src');img.alt='Archive image unavailable'};img.src=p.photo||'';img.alt=p.photo?`Archive photo associated with ${p.name}`:'Archive image unavailable'};$('#details-zone').textContent=`${p.zone||'Kolkata'} Kolkata · ${p.tag||'Discovery listing'}`;$('#details-title').textContent=p.name;$('#details-summary').textContent=`Explore ${p.name} in ${p.area||'Kolkata'}, ${p.zone||'Kolkata'} Kolkata.`;$('#details-area').textContent=p.area||'Kolkata';$('#details-zone-fact').textContent=p.zone||'Kolkata';$('#details-rating').textContent=Number(p.rating)>0?`${Number(p.rating).toFixed(1)} / 5`:'Not rated';$('#details-directions').href=maps(p);const inRoute=window.routeStops?.some?.(x=>x.name===p.name);const r=$('#details-route');r.textContent=inRoute?'Added ✓':'Add to Puja Night +';r.disabled=!!inRoute;modal.hidden=false;modal.setAttribute('aria-hidden','false');modal.classList.add('open');document.body.style.overflow='hidden';requestAnimationFrame(()=>modal.querySelector('.pandal-details-close')?.focus())}
function closeDetails(){modal.classList.remove('open');modal.hidden=true;modal.setAttribute('aria-hidden','true');document.body.style.overflow='';lastFocus?.focus?.();lastFocus=null;current=null}
document.addEventListener('click',e=>{const card=e.target.closest?.('#pandal-list .pandal-card');if(card&&!e.target.closest('a,button'))openDetails(card.dataset.name)});
modal.querySelectorAll('[data-details-close]').forEach(el=>el.addEventListener('click',closeDetails));
$('#details-route')?.addEventListener('click',()=>{if(current&&window.addToRoute){window.addToRoute(current);$('#details-route').textContent='Added ✓';$('#details-route').disabled=true}});
document.addEventListener('keydown',e=>{if(modal.hidden)return;if(e.key==='Escape'){e.preventDefault();closeDetails();return}if(e.key==='Tab'){const items=[...modal.querySelectorAll('button:not([disabled]),a[href],textarea,input,[tabindex]:not([tabindex="-1"])')].filter(x=>x.offsetParent!==null);if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function syncRouteLinks(){const m=mode();document.querySelectorAll('#pandal-list .pandal-card[data-name]').forEach(card=>{const p=find(card.dataset.name),link=card.querySelector('.route');if(!p||!link)return;link.href=maps(p)})}
addEventListener('kolkata:state',syncRouteLinks);addEventListener('load',syncRouteLinks,{once:true});if(document.readyState!=='loading')syncRouteLinks();else addEventListener('DOMContentLoaded',syncRouteLinks,{once:true});
})();
