(()=>{
'use strict';
const list=document.querySelector('#pandal-list');if(!list)return;
const STORAGE='kolkata-pujo-favourites-v1';
let favourites=new Set(),userPos=null,sortMode='recommended',verifiedOnly=false,nearbyOnly=false,applying=false,observer;
try{favourites=new Set(JSON.parse(localStorage.getItem(STORAGE)||'[]'))}catch{}
const hav=(a,b)=>{const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
const getP=name=>window.pandals?.find?.(p=>p.name===name)||null;
const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify([...favourites]))}catch{}};
const isVerified=p=>Boolean(p&&window.KOLKATA_CANONICAL_PINS?.[p.name]&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng)));
function addStyles(){if(document.getElementById('explorer-v2-css'))return;const s=document.createElement('style');s.id='explorer-v2-css';s.textContent=`.explorer-v2-tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:0 0 12px;padding:10px 0}.explorer-v2-tools select,.explorer-v2-tools button{min-height:42px;border:1px solid var(--line,#d9d2c7);border-radius:8px;background:var(--paper,#f7f4ee);color:var(--ink,#181512);padding:9px 13px;font:inherit;cursor:pointer}.explorer-v2-tools button.active{background:var(--ink,#181512);color:#fff}.explorer-v2-tools .v2-spacer{flex:1}.explorer-v2-status{font-size:11px;color:var(--muted,#6e685f);margin:2px 0 12px}.v2-fav{position:absolute;right:10px;top:10px;z-index:4;width:38px;height:38px;border-radius:50%;border:1px solid rgba(24,21,18,.15);background:rgba(255,255,255,.92);color:var(--ink,#181512);font-size:18px;cursor:pointer}.v2-fav.is-fav{background:var(--ink,#181512);color:#fff}.v2-distance{display:inline-block;margin-left:5px;color:var(--muted,#6e685f)}.pandal-card.v2-hidden{display:none!important}@media(max-width:600px){.explorer-v2-tools{position:sticky;top:72px;z-index:31;background:rgba(247,244,238,.96);backdrop-filter:blur(12px);overflow:auto;flex-wrap:nowrap}.explorer-v2-tools>*{flex:0 0 auto}.explorer-v2-tools .v2-spacer{display:none}}`;document.head.appendChild(s)}
function tools(){if(document.querySelector('.explorer-v2-tools'))return;const host=document.querySelector('.explorer-toolbar');if(!host)return;const box=document.createElement('div');box.className='explorer-v2-tools';box.innerHTML='<select id="v2-sort" aria-label="Sort pandals"><option value="recommended">Sort: Recommended</option><option value="distance">Sort: Nearest first</option><option value="rating">Sort: Highest rated</option><option value="name">Sort: A–Z</option><option value="area">Sort: Neighbourhood</option></select><button id="v2-verified" type="button">Exact pins</button><button id="v2-nearby" type="button">Near me</button><button id="v2-favs" type="button">Saved</button><button id="v2-location" type="button">Use my location</button><span class="v2-spacer"></span>';host.after(box);box.querySelector('#v2-sort').addEventListener('change',e=>{sortMode=e.target.value;apply()});box.querySelector('#v2-verified').addEventListener('click',e=>{verifiedOnly=!verifiedOnly;e.currentTarget.classList.toggle('active',verifiedOnly);apply()});box.querySelector('#v2-nearby').addEventListener('click',e=>{if(!userPos){locate(()=>{nearbyOnly=true;e.currentTarget.classList.add('active');apply()});return}nearbyOnly=!nearbyOnly;e.currentTarget.classList.toggle('active',nearbyOnly);apply()});box.querySelector('#v2-favs').addEventListener('click',e=>{const on=e.currentTarget.classList.toggle('active');e.currentTarget.textContent=on?'Saved only':'Saved';apply()});box.querySelector('#v2-location').addEventListener('click',()=>locate())}
function locate(done){if(!navigator.geolocation){status('Location is not available in this browser.');return}status('Requesting your location…');navigator.geolocation.getCurrentPosition(pos=>{userPos={lat:pos.coords.latitude,lng:pos.coords.longitude};status('Location ready · distances are approximate straight-line distances.');apply();done?.()},()=>status('Location permission was not granted. You can still use the explorer normally.'),{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
function status(text){let el=document.querySelector('.explorer-v2-status');if(!el){el=document.createElement('p');el.className='explorer-v2-status';document.querySelector('.explorer-v2-tools')?.after(el)}el.textContent=text}
function ensureVerifiedCards(){const existing=new Set([...list.querySelectorAll('.pandal-card')].map(card=>card.dataset.name));const missing=(window.pandals||[]).filter(p=>isVerified(p)&&!existing.has(p.name));if(!missing.length)return;const fragment=document.createDocumentFragment();missing.forEach(p=>{const card=document.createElement('article');card.className='pandal-card catalog-card';card.dataset.name=p.name;card.tabIndex=0;card.setAttribute('aria-label',`Explore ${p.name}`);card.innerHTML=`<div class="pandal-card-body"><div class="pandal-meta">${String(p.zone||'Kolkata')} · ${String(p.area||'Kolkata')}</div><h3>${String(p.name)}</h3><div class="pin-status verified">● Exact map pin verified</div><div class="rating">● Map pin verified</div><div class="pandal-actions"><button class="catalog-map" type="button">View map</button><button class="catalog-route" type="button">Add to route +</button><a class="route" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${p.lat},${p.lng}`)}&travelmode=walking" target="_blank" rel="noopener">Directions ↗</a></div></div>`;fragment.appendChild(card)});list.appendChild(fragment)}
function syncCounts(){const cards=[...list.querySelectorAll('.pandal-card')];const verified=cards.filter(c=>isVerified(getP(c.dataset.name))).length;const count=document.querySelector('#pandal-result-count');if(count)count.textContent=`${cards.length} pandals in the discovery catalog · ${verified} verified map pins`;const ranking=document.querySelector('#pro-ranking');if(ranking){const ranks=ranking.querySelectorAll('.pro-rank');if(ranks[0])ranks[0].querySelector('strong').textContent=String(verified);if(ranks[1])ranks[1].querySelector('strong').textContent=String(cards.length);if(ranks[2])ranks[2].querySelector('strong').textContent=String(favourites.size)}}
function decorateCard(card){const name=card.dataset.name;if(!name)return;let fav=card.querySelector('.v2-fav');if(!fav){fav=document.createElement('button');fav.className='v2-fav';fav.type='button';card.prepend(fav);fav.addEventListener('click',e=>{e.stopPropagation();favourites.has(name)?favourites.delete(name):favourites.add(name);save();paintFavourite(fav,name);apply()})}paintFavourite(fav,name);const p=getP(name),meta=card.querySelector('.pandal-meta');if(meta&&p?.lat&&userPos&&!meta.querySelector('.v2-distance')){const d=document.createElement('span');d.className='v2-distance';d.textContent=`· ${hav(userPos,p).toFixed(1)} km`;meta.appendChild(d)}}
function paintFavourite(btn,name){const on=favourites.has(name);btn.classList.toggle('is-fav',on);btn.textContent=on?'★':'☆';btn.setAttribute('aria-label',on?`Remove ${name} from saved pandals`:`Save ${name}`)}
function apply(){if(applying)return;applying=true;observer?.disconnect();try{ensureVerifiedCards();const cards=[...list.querySelectorAll('.pandal-card')];const favOnly=document.querySelector('#v2-favs')?.classList.contains('active');cards.forEach(decorateCard);const visible=cards.filter(c=>{const name=c.dataset.name,p=getP(name),dist=userPos&&p?.lat?hav(userPos,p):Infinity;const ok=(!verifiedOnly||isVerified(p))&&(!nearbyOnly||Boolean(userPos&&p?.lat&&dist<=5))&&(!favOnly||favourites.has(name));c.classList.toggle('v2-hidden',!ok);return ok});visible.sort((a,b)=>{const pa=getP(a.dataset.name)||{},pb=getP(b.dataset.name)||{};if(sortMode==='name')return a.dataset.name.localeCompare(b.dataset.name);if(sortMode==='area')return String(pa.area||'').localeCompare(String(pb.area||''));if(sortMode==='rating')return (Number(pb.rating)||0)-(Number(pa.rating)||0);if(sortMode==='distance'){const da=userPos&&pa.lat?hav(userPos,pa):Infinity,db=userPos&&pb.lat?hav(userPos,pb):Infinity;return da-db}return 0});const frag=document.createDocumentFragment();visible.forEach(c=>frag.appendChild(c));list.appendChild(frag);syncCounts();status(`${visible.length} shown · ${cards.length-visible.length} filtered${favourites.size?` · ${favourites.size} saved`:''}`)}finally{applying=false;observer?.observe(list,{childList:true})}}
function boot(){addStyles();tools();observer=new MutationObserver(()=>{if(!applying)requestAnimationFrame(()=>apply())});observer.observe(list,{childList:true});apply()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
