(()=>{
'use strict';
const GUIDES=[
 {id:'north',kicker:'NORTH KOLKATA',title:'Old Kolkata, on foot',copy:'Kumartuli, Bagbazar and Shobhabazar make a compact first evening with heritage, artisans and classic neighbourhood Pujo.',stops:['Kumartuli Park','Bagbazar Sarbojanin','Ahiritola Sarbojanin','Shobhabazar Rajbari','Kashi Bose Lane']},
 {id:'south',kicker:'SOUTH KOLKATA',title:'Lights, themes & adda',copy:'A south-side evening linking Chetla, Ballygunge and Gariahat without turning the night into a cross-city taxi ride.',stops:['Chetla Agrani','Deshapriya Park','Ballygunge Cultural Association','Ekdalia Evergreen','Hindusthan Park']},
 {id:'central',kicker:'CENTRAL KOLKATA',title:'College Street after dark',copy:'A tighter central route for a shorter night: College Street, Sealdah and the classic southward finish at Maddox.',stops:['College Square','Santosh Mitra Square','Maddox Square']},
 {id:'heritage',kicker:'HERITAGE',title:'Courtyards & old stories',copy:'A slower route built around older Kolkata, ideal when you want the history of Pujo as much as the spectacle.',stops:['Shobhabazar Rajbari','Kumartuli Park','Bagbazar Sarbojanin','Ahiritola Sarbojanin']}
];
const NEWS=[
 {kicker:'TRAFFIC WATCH · 15 SEP',title:'Police are preparing for heavier Puja footfall',copy:'Kolkata Police are planning for new or expanded crowd-pullers around Allen Park, New Market and Triangular Park. Expect route and parking plans to evolve as Puja approaches.',meta:'Planning signal · Sep 14–15, 2026',href:'https://timesofindia.indiatimes.com/city/kolkata/puja-closure-for-camac-st-allen-park-stretch/articleshow/134246574.cms',source:'Times of India'},
 {kicker:'FESTIVAL SCALE · 15 SEP',title:'Bengal could cross 65,000 community Pujas',copy:'The 2026 count is expected to rise by about 5,000, with peak electricity demand projected above 14,000 MW on October 13.',meta:'Power preparedness · Oct 13 projection',href:'https://timesofindia.indiatimes.com/city/kolkata/5k-more-pujas-this-yr-power-demand-to-spike/articleshow/134246576.cms',source:'Times of India'},
 {kicker:'TRANSPORT · 13 SEP',title:'10 pairs of special trains announced for the festival rush',copy:'Eastern Railway has announced special services for the Durga Puja, Diwali and Chhath season, with several services originating from Howrah, Sealdah and Kolkata.',meta:'Rail update · booking dates to follow',href:'https://indianexpress.com/article/cities/kolkata/bengal-special-trains-puja-diwali-chhath-10876187/',source:'The Indian Express'},
 {kicker:'WEATHER · 15 SEP',title:'Kolkata gets a quieter weather window',copy:'The latest outlook indicates partly cloudy skies and possible light to moderate rain over Kolkata in the next 24 hours, with no heavy rain currently expected.',meta:'Local outlook · Sep 15, 2026',href:'https://bengali.indianexpress.com/west-bengal/west-bengal-weather-forecast-next-24-hours-12533297',source:'The Indian Express'},
 {kicker:'EDEN GARDENS · 12 SEP',title:'A large Mahalaya opening is planned at Eden Gardens',copy:'A major pre-Puja programme is being prepared around September 25–October 15, with the main Mahalaya event planned for October 10.',meta:'Event planning · Sep 25–Oct 15',href:'https://indianexpress.com/article/cities/kolkata/durga-puja-2026-kolkata-eden-gardens-pm-modi-mahalaya-10875267/',source:'The Indian Express'},
 {kicker:'PARKING · 09 SEP',title:'Traffic Police are hunting for more parking near major pandals',copy:'Officials are planning additional parking options as several crowd-puller pandals may see significantly higher visitor numbers. Illegal parking will face stricter enforcement from Chaturthi.',meta:'Visitor planning · central & south Kolkata',href:'https://timesofindia.indiatimes.com/city/kolkata/cops-hunt-for-more-parking-spaces-near-durga-puja-pandals/articleshow/133980203.cms',source:'Times of India'}
];
function style(){if(document.getElementById('puja-guide-styles'))return;const s=document.createElement('style');s.id='puja-guide-styles';s.textContent=`
.site-header{position:fixed!important;top:0;left:0;right:0;z-index:1000;min-height:68px;padding:10px clamp(18px,4vw,54px);display:flex;align-items:center;gap:28px;background:rgba(20,12,10,.72);backdrop-filter:blur(16px) saturate(120%);-webkit-backdrop-filter:blur(16px) saturate(120%);border-bottom:1px solid rgba(255,255,255,.12);transition:background .25s ease,box-shadow .25s ease}
.site-header .brand{display:flex;align-items:center;gap:10px;white-space:nowrap;text-decoration:none;color:#fff!important}.site-header .brand-bengali{font-family:'Noto Serif Bengali',serif;font-weight:700;font-size:clamp(16px,1.5vw,20px)}.site-header .brand small{font:700 10px/1 'DM Sans',sans-serif;letter-spacing:.16em;text-transform:uppercase;opacity:.65;border-left:1px solid rgba(255,255,255,.3);padding-left:10px}
.site-header nav{margin-left:auto;display:flex;align-items:center;gap:4px}.site-header nav a{position:relative;padding:9px 12px!important;border-radius:999px;color:rgba(255,255,255,.78)!important;text-decoration:none;font:600 12px/1 'DM Sans',sans-serif;transition:color .2s ease,background .2s ease}.site-header nav a:hover,.site-header nav a:focus-visible{color:#fff!important;background:rgba(255,255,255,.1)}.site-header nav a.nav-route{color:#1d1511!important;background:#f7f4ee!important;padding:10px 16px!important;margin-left:7px}.site-header nav a.nav-route:hover{background:#fff!important;transform:translateY(-1px)}.site-header .menu{border:1px solid rgba(255,255,255,.22)!important;border-radius:999px;background:rgba(255,255,255,.08)!important;color:#fff!important}
@media(max-width:800px){.site-header{min-height:64px;padding:8px 14px}.site-header nav{top:70px!important;right:14px!important;left:14px!important;width:auto!important;min-width:0!important;padding:8px!important;background:rgba(247,244,238,.98)!important;box-shadow:0 18px 45px rgba(24,21,18,.22)!important;border:1px solid rgba(24,21,18,.12)!important}.site-header nav a{color:#181512!important;border-radius:9px!important;padding:13px 14px!important}.site-header nav a.nav-route{margin:4px 0 0!important;text-align:center}}
.puja-guides{margin:34px 0 24px;padding:26px;border:1px solid rgba(24,21,18,.12);background:rgba(247,244,238,.72)}.puja-guides-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:18px}.puja-guides-head h3{margin:0;font:600 clamp(24px,3vw,38px)/1.05 'Playfair Display',serif}.puja-guides-head p{max-width:480px;margin:0;color:#6f665e;font-size:14px;line-height:1.6}.puja-guides-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.puja-guide-card{padding:18px;background:#fff;border:1px solid rgba(24,21,18,.1);display:flex;flex-direction:column;min-height:220px}.puja-guide-card .guide-kicker{font-size:10px;letter-spacing:.16em;font-weight:700;color:#8b3f2d}.puja-guide-card h4{font:600 22px/1.1 'Playfair Display',serif;margin:10px 0 8px}.puja-guide-card p{font-size:13px;line-height:1.55;color:#6f665e;margin:0 0 14px}.puja-guide-stops{font-size:11px;line-height:1.5;color:#3f3934;margin-bottom:14px}.puja-guide-card button{margin-top:auto;border:0;background:#181512;color:#fff;padding:11px 13px;font:600 12px/1 'DM Sans',sans-serif;cursor:pointer}.puja-guide-card button:disabled{opacity:.45;cursor:not-allowed}
.puja-pulse{margin:34px 0 24px;padding:26px;border:1px solid #ded6ca;background:linear-gradient(145deg,#fffdfa,#f3eee6);box-shadow:0 16px 45px rgba(24,21,18,.06)}.puja-pulse-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:18px}.puja-pulse-head h3{margin:0;font:600 clamp(26px,3vw,40px)/1.04 'Playfair Display',serif}.puja-pulse-head p{max-width:500px;margin:0;color:#6f665e;font-size:13px;line-height:1.6}.pulse-badge{display:inline-flex;margin-top:9px;padding:5px 9px;border-radius:999px;background:rgba(180,49,34,.08);color:#8f2419;font:700 10px/1 'DM Sans',sans-serif;letter-spacing:.1em;text-transform:uppercase}.pulse-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.pulse-card{padding:18px;background:#fff;border:1px solid #e0d9cf;border-radius:14px;min-height:205px}.pulse-card.featured{background:#1b1714;color:#fff;border-color:#2c2520}.pulse-kicker{font:700 9px/1 'DM Sans',sans-serif;letter-spacing:.15em;text-transform:uppercase;color:#b43122}.featured .pulse-kicker{color:#e0b96f}.pulse-card h4{margin:10px 0 8px;font:600 21px/1.14 'Playfair Display',serif}.pulse-card p{margin:0;color:#6f665e;font-size:13px;line-height:1.55}.featured p{color:#d9d1c7}.pulse-meta{margin-top:14px;padding-top:12px;border-top:1px solid rgba(24,21,18,.1);font-size:10px;line-height:1.45;color:#81786f}.featured .pulse-meta{border-color:rgba(255,255,255,.12);color:#bcb2a8}.pulse-link{display:inline-flex;margin-top:13px;color:#8f2419;font-size:11px;font-weight:700;text-decoration:none}.featured .pulse-link{color:#f0cc91}.pulse-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.pulse-fact{padding:12px;border-radius:10px;background:#f4efe8}.pulse-fact strong{display:block;font:700 20px/1 'Playfair Display',serif;color:#181512}.pulse-fact span{display:block;margin-top:4px;color:#756d63;font-size:10px;line-height:1.3}.pulse-source{margin:14px 0 0;color:#8a8177;font-size:10px;line-height:1.5}.pulse-source a{color:inherit}.pulse-tip{margin:12px 0 0;padding:12px 14px;border-radius:10px;background:#1b1714;color:#ddd2c7;font-size:11px;line-height:1.5}.pulse-tip strong{color:#f0cc91}
@media(max-width:900px){.puja-guides-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pulse-grid{grid-template-columns:1fr 1fr}.pulse-card.featured{grid-column:1/-1}.pulse-facts{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.puja-guides{padding:18px}.puja-guides-head,.puja-pulse-head{display:block}.puja-guides-head p,.puja-pulse-head p{margin-top:8px}.puja-guides-grid,.pulse-grid{grid-template-columns:1fr}.puja-guide-card{min-height:0}.puja-pulse{padding:18px}.pulse-card.featured{grid-column:auto}.pulse-facts{grid-template-columns:1fr 1fr}.pulse-fact:last-child{grid-column:auto}}
`;document.head.appendChild(s)}
function setupNav(){const nav=document.querySelector('.site-header nav');if(!nav||nav.dataset.pujaNavReady==='true')return;nav.dataset.pujaNavReady='true';if(!nav.querySelector('.nav-route')){const a=document.createElement('a');a.className='nav-route';a.href='#route-planner';a.textContent='Plan a route';nav.appendChild(a)}if(!nav.querySelector('a[href="#puja-guides"]')){const a=document.createElement('a');a.href='#puja-guides';a.textContent='Routes';nav.insertBefore(a,nav.querySelector('.nav-route'))}const menu=document.querySelector('.site-header .menu');const close=()=>{if(menu?.getAttribute('aria-expanded')==='true')menu.click()};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setTimeout(close,0)));const header=document.querySelector('.site-header');window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>24),{passive:true})}
function renderGuides(){const anchor=document.querySelector('.explorer-layout');if(!anchor||document.getElementById('puja-guides'))return;const section=document.createElement('section');section.id='puja-guides';section.className='puja-guides';section.innerHTML=`<div class="puja-guides-head"><div><div class="section-label">ROUTE-FIRST PUJO</div><h3>Choose a night, not a giant list.</h3></div><p>Start with one neighbourhood cluster, load the stops, then refine the route below.</p></div><div class="puja-guides-grid">${GUIDES.map(g=>`<article class="puja-guide-card"><span class="guide-kicker">${g.kicker}</span><h4>${g.title}</h4><p>${g.copy}</p><div class="puja-guide-stops">${g.stops.join(' · ')}</div><button type="button" data-load-guide="${g.id}">Add ${g.stops.length} stops to route</button></article>`).join('')}</div>`;anchor.after(section);section.addEventListener('click',e=>{const b=e.target.closest('[data-load-guide]');if(!b)return;const g=GUIDES.find(x=>x.id===b.dataset.loadGuide);if(!g||typeof window.addToRoute!=='function')return;let added=0;g.stops.forEach(name=>{const p=window.pandals?.find?.(x=>x.name===name);if(p&&!window.routeStops.some(x=>x.name===name)&&window.routeStops.length<8){window.addToRoute(p);added++}});b.textContent=added?`Loaded ${added} stops — route is ready`:'Stops already in your route';b.disabled=true;setTimeout(()=>{b.textContent=`Add ${g.stops.length} stops to route`;b.disabled=false},1800);document.querySelector('#route-planner')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function renderPulse(){const anchor=document.querySelector('#puja-2026-info');if(!anchor||document.getElementById('puja-pulse'))return;const section=document.createElement('section');section.id='puja-pulse';section.className='puja-pulse';section.setAttribute('aria-label','Latest Kolkata Puja news and city pulse');section.innerHTML=`<div class="puja-pulse-head"><div><div class="section-label">05 / CITY PULSE</div><h3>What's moving in Kolkata.</h3><span class="pulse-badge">Fresh · 15 September 2026</span></div><p>Current planning signals for visitors. Headlines are summaries; open the source before relying on a road, rail or event detail.</p></div><div class="pulse-grid">${NEWS.map((n,i)=>`<article class="pulse-card ${i===0?'featured':''}"><div class="pulse-kicker">${n.kicker}</div><h4>${n.title}</h4><p>${n.copy}</p><div class="pulse-meta">${n.meta}</div><a class="pulse-link" href="${n.href}" target="_blank" rel="noopener noreferrer">Read source · ${n.source} ↗</a></article>`).join('')}</div><div class="pulse-facts"><div class="pulse-fact"><strong>10 Oct</strong><span>Mahalaya</span></div><div class="pulse-fact"><strong>16 Oct</strong><span>Maha Panchami</span></div><div class="pulse-fact"><strong>19 Oct</strong><span>Maha Ashtami</span></div><div class="pulse-fact"><strong>21 Oct</strong><span>Vijaya Dashami</span></div></div><div class="pulse-tip"><strong>Route tip:</strong> parking is already being treated as a major Puja constraint. Prefer neighbourhood clusters, public transport and walking for dense zones.</div><p class="pulse-source">Official date reference: <a href="https://aasan.wb.gov.in/" target="_blank" rel="noopener noreferrer">West Bengal AASAN Puja Permission Portal</a>. News checked 15 September 2026.</p>`;anchor.before(section)}
function boot(){style();setupNav();renderGuides();renderPulse()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100),{once:true});else setTimeout(boot,100);
})();