(()=>{
'use strict';
const GUIDES=[
 {id:'north',kicker:'NORTH KOLKATA',title:'Old Kolkata, on foot',copy:'Kumartuli, Bagbazar and Shobhabazar make a compact first evening with heritage, artisans and classic neighbourhood Pujo.',stops:['Kumartuli Park','Bagbazar Sarbojanin','Ahiritola Sarbojanin','Shobhabazar Rajbari','Kashi Bose Lane']},
 {id:'south',kicker:'SOUTH KOLKATA',title:'Lights, themes & adda',copy:'A south-side evening linking Chetla, Ballygunge and Gariahat without turning the night into a cross-city taxi ride.',stops:['Chetla Agrani','Deshapriya Park','Ballygunge Cultural Association','Ekdalia Evergreen','Hindusthan Park']},
 {id:'central',kicker:'CENTRAL KOLKATA',title:'College Street after dark',copy:'A tighter central route for a shorter night: College Street, Sealdah and the classic southward finish at Maddox.',stops:['College Square','Santosh Mitra Square','Maddox Square']},
 {id:'heritage',kicker:'HERITAGE',title:'Courtyards & old stories',copy:'A slower route built around older Kolkata, ideal when you want the history of Pujo as much as the spectacle.',stops:['Shobhabazar Rajbari','Kumartuli Park','Bagbazar Sarbojanin','Ahiritola Sarbojanin']}
];
function style(){if(document.getElementById('puja-guide-styles'))return;const s=document.createElement('style');s.id='puja-guide-styles';s.textContent=`
.puja-guides{margin:34px 0 24px;padding:26px;border:1px solid rgba(24,21,18,.12);background:rgba(247,244,238,.72)}
.puja-guides-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:18px}.puja-guides-head h3{margin:0;font:600 clamp(24px,3vw,38px)/1.05 'Playfair Display',serif}.puja-guides-head p{max-width:480px;margin:0;color:#6f665e;font-size:14px;line-height:1.6}
.puja-guides-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.puja-guide-card{padding:18px;background:#fff;border:1px solid rgba(24,21,18,.1);display:flex;flex-direction:column;min-height:220px}.puja-guide-card .guide-kicker{font-size:10px;letter-spacing:.16em;font-weight:700;color:#8b3f2d}.puja-guide-card h4{font:600 22px/1.1 'Playfair Display',serif;margin:10px 0 8px}.puja-guide-card p{font-size:13px;line-height:1.55;color:#6f665e;margin:0 0 14px}.puja-guide-stops{font-size:11px;line-height:1.5;color:#3f3934;margin-bottom:14px}.puja-guide-card button{margin-top:auto;border:0;background:#181512;color:#fff;padding:11px 13px;font:600 12px/1 'DM Sans',sans-serif;cursor:pointer}.puja-guide-card button:disabled{opacity:.45;cursor:not-allowed}
@media(max-width:900px){.puja-guides-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.puja-guides{padding:18px}.puja-guides-head{display:block}.puja-guides-head p{margin-top:8px}.puja-guides-grid{grid-template-columns:1fr}.puja-guide-card{min-height:0}}
`;document.head.appendChild(s)}
function render(){const anchor=document.querySelector('.explorer-layout');if(!anchor||document.getElementById('puja-guides'))return;style();const section=document.createElement('section');section.id='puja-guides';section.className='puja-guides';section.innerHTML=`<div class="puja-guides-head"><div><div class="section-label">ROUTE-FIRST PUJO</div><h3>Choose a night, not a giant list.</h3></div><p>Inspired by neighbourhood-first planning: start with a cluster, save the route, then let the map handle the order.</p></div><div class="puja-guides-grid">${GUIDES.map(g=>`<article class="puja-guide-card" data-guide="${g.id}"><span class="guide-kicker">${g.kicker}</span><h4>${g.title}</h4><p>${g.copy}</p><div class="puja-guide-stops">${g.stops.join(' · ')}</div><button type="button" data-load-guide="${g.id}">Add ${g.stops.length} stops to route</button></article>`).join('')}</div>`;anchor.after(section);section.addEventListener('click',e=>{const b=e.target.closest('[data-load-guide]');if(!b)return;const guide=GUIDES.find(g=>g.id===b.dataset.loadGuide);if(!guide||typeof window.addToRoute!=='function')return;let added=0;guide.stops.forEach(name=>{const p=window.pandals?.find?.(x=>x.name===name);if(p&&!window.routeStops.some(x=>x.name===name)&&window.routeStops.length<8){window.addToRoute(p);added++}});b.textContent=added?'Route loaded — scroll down':'Stops already in your route';b.disabled=true;setTimeout(()=>{b.textContent=`Add ${guide.stops.length} stops to route`;b.disabled=false},1800);document.querySelector('#route-planner')?.scrollIntoView({behavior:'smooth',block:'start'})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,100),{once:true});else setTimeout(render,100);
})();
