(()=>{
'use strict';
const PIN={
 'Bagbazar Sarbojanin':[22.60121,88.36682,'78, Baghbazar Street, Kolkata 700003','Agamoni 2026','reported-2026'],
 'Tala Prattoy':[22.61046,88.38460,'Tala / Belgachia, North Kolkata','Agamoni 2026','reported-2026'],
 'Hatibagan Sarbojanin':[22.59439,88.37200,'Hatibagan, Kolkata','Agamoni 2026','reported-2026'],
 'Sree Bhumi Sporting Club':[22.59890,88.40293,'Sreebhumi, Kolkata','Agamoni 2026','reported-2026'],
 'Dumdum Park Bharat Chakra':[22.61082,88.41460,'Dum Dum Park, Kolkata','Agamoni 2026','reported-2026'],
 'Dumdum Park Sarbojanin':[22.60944,88.41641,'Dum Dum Park, Kolkata','Agamoni 2026','reported-2026'],
 'Kumartuli Park':[22.59898,88.36147,'Kumartuli, Kolkata 700005','Agamoni 2026','reported-2026'],
 'Shobhabazar Rajbari':[22.59626,88.36738,'Raja Nabakrishna Street, Sovabazar, Kolkata 700005','Agamoni 2026','reported-2026'],
 'College Square':[22.57453,88.36447,'College Street, Kolkata','Agamoni 2026','reported-2026'],
 'Santosh Mitra Square':[22.56602,88.36565,'Natabar Dutta Row, Lebutala, Bowbazar, Kolkata 700014','Agamoni 2026','reported-2026'],
 'Maddox Square':[22.52656,88.35465,'Maddox Square, Ballygunge, Kolkata','Agamoni 2026','reported-2026'],
 'Deshapriya Park':[22.51858,88.35346,'Deshapriya Park, Kalighat, Kolkata','Agamoni 2026','reported-2026'],
 'Naktala Udayan Sangha':[22.47449,88.36658,'Naktala, Garia, Kolkata 700047','OpenStreetMap/Mapcarta','reported-2026']
};
const speeds={walking:4.5,driving:20,transit:18,'two-wheeler':24};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hav=(a,b)=>{const R=6371,d1=(b.lat-a.lat)*Math.PI/180,d2=(b.lng-a.lng)*Math.PI/180,x=Math.sin(d1/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
const pointUrl=p=>`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}&travelmode=${encodeURIComponent(localStorage.getItem('kolkata-pujo-mode')||'walking')}`;
const placeUrl=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name}, ${p.area||''}, Kolkata, West Bengal`)}`;
let map,cluster,all=[],nearby=false,userPos=null;
function css(){if(document.getElementById('puja-suite-css'))return;const s=document.createElement('style');s.id='puja-suite-css';s.textContent=`.suite-tools{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0 14px}.suite-tools button{min-height:44px;padding:10px 14px;border:1px solid rgba(243,234,217,.2);border-radius:999px;background:transparent;color:inherit;font:inherit;cursor:pointer}.suite-tools button.active{background:#f3ead9;color:#140c0a}.suite-status{font-size:11px;opacity:.6;margin:6px 0 12px}.suite-source{font-size:10px;opacity:.58}.suite-live{margin-top:18px;padding:16px;border:1px solid rgba(216,173,98,.32);border-radius:18px;background:rgba(216,173,98,.06)}.suite-live-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.suite-live-card{padding:12px;border:1px solid rgba(243,234,217,.12);border-radius:12px}.suite-live-card small{display:block;text-transform:uppercase;letter-spacing:.08em;opacity:.5}.suite-live-card p{font-size:12px;line-height:1.5}.suite-route{margin-top:12px;padding:12px;border:1px solid rgba(243,234,217,.14);border-radius:14px}.suite-route-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.suite-route-grid strong{display:block;font-size:16px}.suite-route-grid span{font-size:9px;opacity:.55;text-transform:uppercase;letter-spacing:.08em}.suite-route button{min-height:44px;margin-top:10px;border:1px solid rgba(243,234,217,.2);border-radius:999px;background:transparent;color:inherit;padding:9px 13px}.leaflet-popup-content{font:13px/1.45 var(--sans,Arial,sans-serif)}.leaflet-popup-content img{width:100%;height:92px;object-fit:cover;border-radius:8px;margin-bottom:7px}.leaflet-popup-content button{min-height:38px}.map-panel{overflow:hidden}@media(max-width:800px){.suite-tools{position:sticky;top:145px;z-index:30;overflow:auto;flex-wrap:nowrap;padding:8px 0;background:rgba(247,244,238,.96);backdrop-filter:blur(12px)}.suite-tools button{white-space:nowrap}.suite-live-grid,.suite-route-grid{grid-template-columns:1fr}.map-panel{height:52vh;min-height:330px}.map-panel #pandal-map{height:100%;min-height:330px}}@media(max-width:420px){.suite-tools button{font-size:12px;padding-inline:12px}}`;document.head.appendChild(s)}
function data(){const cards=[...document.querySelectorAll('#pandal-list .pandal-card')];const seen=new Set();return cards.map(c=>{const name=c.dataset.name;if(seen.has(name))return null;seen.add(name);const m=c.querySelector('.pandal-meta')?.textContent.split('·').map(x=>x.trim())||[];const v=PIN[name];const img=c.querySelector('img')?.src||'';return{name,zone:m[0]||'',area:(m[1]||'').replace(/\s+·.*$/,''),photo:img,lat:v?.[0],lng:v?.[1],address:v?.[2]||'',source:v?.[3]||'',status:v?.[4]||'pending',rating:(window.pandals?.find?.(p=>p.name===name)?.rating)||0}}).filter(Boolean)}
function injectVerifiedIntoCore(){if(!Array.isArray(window.pandals))return;Object.entries(PIN).forEach(([name,v])=>{if(!window.pandals.some(p=>p.name===name)){const card=document.querySelector(`#pandal-list .pandal-card[data-name="${CSS.escape(name)}"]`);window.pandals.push({name,zone:card?.querySelector('.pandal-meta')?.textContent.split('·')[0]?.trim()||'North',area:card?.querySelector('.pandal-meta')?.textContent.split('·')[1]?.trim()||'',lat:v[0],lng:v[1],tag:'Verified location',photo:card?.querySelector('img')?.src||'',rating:0});}})}
function fit(){if(!map)return;const pts=all.filter(p=>p.lat).map(p=>[p.lat,p.lng]);if(pts.length)map.fitBounds(pts,{padding:[24,24],maxZoom:13})}
function filtered(){const q=(document.querySelector('#pandal-search')?.value||'').trim().toLowerCase();const z=document.querySelector('#pandal-filters .filter-btn.active')?.dataset.zone||'all';const verified=document.getElementById('suite-verified')?.classList.contains('active');return all.filter(p=>(z==='all'||p.zone===z)&&(!q||`${p.name} ${p.area} ${p.zone}`.toLowerCase().includes(q))&&(!verified||p.lat)&&(!nearby||!userPos||p.lat&&hav(userPos,p)<=3))}
function cardRender(){const list=document.querySelector('#pandal-list');if(!list)return;const items=filtered();list.innerHTML=items.length?items.map(p=>{const pin=!!p.lat,dist=userPos&&pin?` · ${hav(userPos,p).toFixed(1)} km`:'';return `<article class="pandal-card ${pin?'':'pending-pin'}" data-name="${esc(p.name)}" tabindex="0"><img src="${esc(p.photo)}" alt="${esc(p.name)}" loading="lazy" onerror="this.remove()"><div class="pandal-card-body"><div class="pandal-meta">${esc(p.zone)} · ${esc(p.area)}${dist}</div><h3>${esc(p.name)}</h3><div class="pin-status ${pin?'verified':'pending'}">${pin?'● Exact pin · '+esc(p.source):'○ Exact pin pending'}</div><div class="pandal-actions"><button class="suite-map" type="button" ${pin?'':'disabled'}>${pin?'View map':'Map pin pending'}</button>${pin?`<button class="suite-add" type="button">${(window.routeStops||[]).some(x=>x.name===p.name)?'Added ✓':'Add to route +'}</button>`:''}<a class="route" href="${pin?pointUrl(p):placeUrl(p)}" target="_blank" rel="noopener">Directions ↗</a></div></div></article>`}).join(''):'<div class="empty-state"><strong>No pandals match these filters.</strong><p>Clear search or change the zone/nearby filter.</p></div>';const count=document.getElementById('pandal-result-count');if(count)count.innerHTML=`<span class="count-pill">${items.length} shown</span> <span class="count-pill">${all.filter(p=>p.lat).length} exact pins</span> <span class="count-pill">${all.length} discovery listings</span>`;bindCards()}
function bindCards(){document.querySelectorAll('.suite-map').forEach(b=>b.onclick=e=>{e.stopPropagation();focus(all.find(p=>p.name===b.closest('.pandal-card').dataset.name))});document.querySelectorAll('.suite-add').forEach(b=>b.onclick=e=>{e.stopPropagation();const p=all.find(p=>p.name===b.closest('.pandal-card').dataset.name);if(p&&window.addToRoute)window.addToRoute({...p});setTimeout(cardRender,20)});document.querySelectorAll('#pandal-list .pandal-card').forEach(c=>c.onclick=e=>{if(e.target.closest('button,a'))return;const p=all.find(x=>x.name===c.dataset.name);if(p?.lat)focus(p)})}
function focus(p){if(!p?.lat||!map)return;map.setView([p.lat,p.lng],15,{animate:true});const m=cluster?cluster.getLayers().find(x=>x.options.title===p.name):null;m?.openPopup();const c=document.querySelector(`#pandal-list .pandal-card[data-name="${CSS.escape(p.name)}"]`);c?.scrollIntoView({behavior:'smooth',block:'center'});c?.classList.add('selected');setTimeout(()=>c?.classList.remove('selected'),1200)}
function popup(p){const photo=p.photo?`<img src="${esc(p.photo)}" alt="">`:'';const rating=p.rating?`${p.rating.toFixed(1)} / 5 historical rating`:'Rating unavailable';return `${photo}<strong>${esc(p.name)}</strong><br><small>${esc(p.area)} · ${esc(p.zone)}</small><p style="margin:7px 0">${esc(p.address)}<br>${esc(rating)}<br><span class="suite-source">${p.source?'Reported/current listing source':'Archive/discovery listing'} · exact pin</span></p><a href="${pointUrl(p)}" target="_blank" rel="noopener">Directions ↗</a> · <button type="button" data-suite-add="${esc(p.name)}">Add to route</button>`}
function loadCluster(done){if(window.L?.MarkerClusterGroup){done();return}const a=document.createElement('link');a.rel='stylesheet';a.href='https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css';document.head.appendChild(a);const b=document.createElement('link');b.rel='stylesheet';b.href='https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css';document.head.appendChild(b);const s=document.createElement('script');s.src='https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js';s.onload=done;s.onerror=done;document.head.appendChild(s)}
function mapBuild(){const old=document.querySelector('#pandal-map');if(!old||!window.L)return;const fresh=old.cloneNode(false);old.replaceWith(fresh);map=L.map(fresh,{scrollWheelZoom:false,preferCanvas:true,zoomControl:true,fadeAnimation:false,zoomAnimation:false}).setView([22.5726,88.3639],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);cluster=L.markerClusterGroup({showCoverageOnHover:false,maxClusterRadius:48,disableClusteringAtZoom:15});all.filter(p=>p.lat).forEach(p=>{const m=L.marker([p.lat,p.lng],{title:p.name,alt:p.name});m.bindPopup(popup(p));m.on('click',()=>{const c=document.querySelector(`#pandal-list .pandal-card[data-name="${CSS.escape(p.name)}"]`);c?.scrollIntoView({behavior:'smooth',block:'center'});});cluster.addLayer(m)});map.addLayer(cluster);const legend=document.createElement('div');legend.className='map-legend';legend.innerHTML='<strong>Map</strong><br>Exact pins only · clustered when zoomed out';fresh.parentElement.style.position='relative';fresh.parentElement.appendChild(legend);setTimeout(()=>{map.invalidateSize(false);fit()},150)}
function mapSync(){if(!map||!cluster)return;const visible=new Set(filtered().filter(p=>p.lat).map(p=>p.name));cluster.getLayers().forEach(m=>{const show=visible.has(m.options.title);if(show&&!cluster.hasLayer(m))cluster.addLayer(m);if(!show&&cluster.hasLayer(m))cluster.removeLayer(m)});}
function routeUI(){const host=document.querySelector('.route-planner');if(!host||document.getElementById('suite-route'))return;const box=document.createElement('div');box.id='suite-route';box.className='suite-route';box.innerHTML='<div class="suite-route-grid"><div><strong id="suite-distance">0 km</strong><span>estimated distance</span></div><div><strong id="suite-time">0 min</strong><span>estimated time</span></div><div><strong id="suite-stops">0</strong><span>saved stops</span></div></div><button type="button" id="suite-optimize">Optimize order</button><p class="route-hint">Estimates use straight-line stop-to-stop distance and typical urban speeds; live traffic/transit times are not claimed.</p>';host.appendChild(box);box.querySelector('#suite-optimize').onclick=optimize}
function routeStats(){const r=window.routeStops||[];let km=0;for(let i=1;i<r.length;i++)if(r[i-1].lat&&r[i].lat)km+=hav(r[i-1],r[i]);const m=(document.querySelector('.mode-btn.active')?.dataset.mode||'walking');const min=km/(speeds[m]||4.5)*60;document.getElementById('suite-distance')&&(document.getElementById('suite-distance').textContent=`${km.toFixed(1)} km`);document.getElementById('suite-time')&&(document.getElementById('suite-time').textContent=km?`${Math.max(1,Math.round(min))} min`:'0 min');document.getElementById('suite-stops')&&(document.getElementById('suite-stops').textContent=r.length)}
function optimize(){const r=window.routeStops;if(!Array.isArray(r)||r.length<3){routeStats();return}const remaining=r.slice(1),out=[r[0]];while(remaining.length){const cur=out[out.length-1];let bi=0,bd=Infinity;remaining.forEach((p,i)=>{const d=hav(cur,p);if(d<bd){bd=d;bi=i}});out.push(remaining.splice(bi,1)[0])}r.splice(0,r.length,...out);try{localStorage.setItem('kolkata-pujo-route',JSON.stringify(r.map(p=>({name:p.name}))));}catch{}document.querySelector('#route-stops')?.replaceChildren(...r.map((p,i)=>{const d=document.createElement('div');d.className='route-stop';d.innerHTML=`<span class="route-stop-index">${i+1}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.area||'')}</small></div><button class="remove-stop" type="button" aria-label="Remove ${esc(p.name)}">×</button>`;d.querySelector('button').onclick=()=>{r.splice(i,1);routeStats();d.remove();};return d}));routeStats()}
function liveLayer(){const sec=document.querySelector('#puja-2026-info');if(!sec||document.getElementById('suite-live'))return;const d=document.createElement('div');d.id='suite-live';d.className='suite-live';d.innerHTML='<strong>2026 live layer</strong><div class="suite-live-grid"><article class="suite-live-card"><small>Official · 7 Sep</small><p>West Bengal announced ₹1 lakh for small/low-budget committees, free electricity and fire-licence fee waiver; DJs remain prohibited during Puja and immersion.</p><a href="https://wb.gov.in/government-cm-events-details-new.aspx?event=Durga-Puja-2026-Meeting&id=E260908105535364" target="_blank" rel="noopener">Government of West Bengal ↗</a></article><article class="suite-live-card"><small>Official calendar</small><p>State holiday records place Maha Shashthi on 17 Oct and Dashami on 21 Oct, with additional Puja days on 22–24 Oct. Core public-facing festival dates should follow the state record.</p><a href="https://wb.gov.in/pdf/Holiday-2026.pdf" target="_blank" rel="noopener">West Bengal holiday PDF ↗</a></article><article class="suite-live-card"><small>Reported · 2026</small><p>Current public listings are treated as reported/discovery information unless an official committee source is available. Unverified pandal pins stay pending.</p><a href="https://kolkatakhoj.com/durga-puja-2026/" target="_blank" rel="noopener">2026 public listing ↗</a></article></div><p class="route-hint">No live traffic feed is claimed here. When official traffic advisories are published, they should be added as dated updates rather than presented as permanent facts.</p>';sec.appendChild(d)}
function seo(){const set=(n,v,p=false)=>{let e=document.querySelector(p?`meta[property="${n}"]`:`meta[name="${n}"]`);if(!e){e=document.createElement('meta');p?e.setAttribute('property',n):e.setAttribute('name',n);document.head.appendChild(e)}e.content=v};set('description','Kolkata Durga Puja 2026 explorer with 92 discovery listings, exact verified map pins, route planning, Puja Night and dated official guidance.');set('og:title','কলকাতা দুর্গাপূজা — ২০২৬',true);set('og:description','Explore Kolkata Puja 2026 with verified locations, routes and dated guidance.',true);set('og:type','website',true);set('og:url','https://tejas-mk2.github.io/KOLKATA/',true);set('twitter:card','summary');set('twitter:title','কলকাতা দুর্গাপূজা — ২০২৬');set('twitter:description','A practical Kolkata Durga Puja 2026 explorer.');let c=document.querySelector('link[rel=canonical]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c)}c.href='https://tejas-mk2.github.io/KOLKATA/'}
function introFix(){const intro=document.querySelector('.site-intro');if(!intro)return;const s=document.createElement('style');s.id='intro-suite-fix';s.textContent=`.site-intro{animation:none!important;opacity:1!important;visibility:visible!important;pointer-events:none!important;overflow:hidden!important}.site-intro-inner{animation:none!important}.site-intro-kicker,.site-intro-title,.site-intro-year,.site-intro-line{opacity:1!important;transform:none!important;filter:none!important}.site-intro.is-leaving{animation:pujaIntroOut .55s cubic-bezier(.76,0,.24,1) forwards!important}@keyframes pujaIntroOut{from{opacity:1;transform:translateY(0)}to{opacity:0;transform:translateY(-18px)}}@media(prefers-reduced-motion:reduce){.site-intro{display:none!important}}`;document.head.appendChild(s);const done=()=>{intro.classList.add('is-leaving');setTimeout(()=>intro.remove(),580)};setTimeout(done,1550);intro.addEventListener('click',done);}
function start(){css();introFix();seo();injectVerifiedIntoCore();all=data();const count=document.getElementById('pandal-result-count');if(count)count.innerHTML=`<span class="count-pill">${all.length} discovery listings</span> <span class="count-pill">${all.filter(p=>p.lat).length} exact pins</span> <span class="count-pill">${all.length-all.filter(p=>p.lat).length} pending verification</span>`;const toolbar=document.querySelector('.explorer-toolbar');if(toolbar&&!document.querySelector('.suite-tools')){const t=document.createElement('div');t.className='suite-tools';t.innerHTML='<button id="suite-nearby" type="button">Show only nearby</button><button id="suite-verified" type="button">Verified pins only</button><button id="suite-fit" type="button">Fit map</button>';toolbar.after(t);t.querySelector('#suite-nearby').onclick=()=>{if(!userPos){if(!navigator.geolocation){alert('Location is unavailable on this device.');return}navigator.geolocation.getCurrentPosition(p=>{userPos={lat:p.coords.latitude,lng:p.coords.longitude};nearby=true;t.querySelector('#suite-nearby').classList.add('active');cardRender();mapSync()},()=>{}, {enableHighAccuracy:false,timeout:8000,maximumAge:300000})}else{nearby=!nearby;t.querySelector('#suite-nearby').classList.toggle('active',nearby);cardRender();mapSync()}};t.querySelector('#suite-verified').onclick=()=>{t.querySelector('#suite-verified').classList.toggle('active');cardRender();mapSync()};t.querySelector('#suite-fit').onclick=fit}routeUI();liveLayer();mapBuild();document.querySelector('#pandal-search')?.addEventListener('input',()=>{cardRender();mapSync()});document.querySelectorAll('#pandal-filters .filter-btn').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{cardRender();mapSync()},0)));document.querySelectorAll('.mode-btn').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('kolkata-pujo-mode',b.dataset.mode||'walking');window.__pujaMode=b.dataset.mode||'walking';routeStats()}));document.addEventListener('click',e=>{const b=e.target.closest?.('[data-suite-add]');if(b){const p=all.find(x=>x.name===b.dataset.suiteAdd);if(p&&window.addToRoute)window.addToRoute({...p});setTimeout(routeStats,20)}});routeStats();setTimeout(()=>{map?.invalidateSize(false);fit()},300)}
let tries=0;const boot=()=>{if(document.querySelectorAll('#pandal-list .pandal-card').length<80&&tries++<15){setTimeout(boot,500);return}start()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();