(()=>{
'use strict';
const storageGet=(key,fallback='')=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const storageSet=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
const mapsMode=()=>{const active=document.querySelector('.mode-btn.active')?.dataset.mode||storageGet('kolkata-pujo-mode','walking');return active==='two-wheeler'?'driving':active};
const rewriteMapsLinks=()=>{const mode=mapsMode();document.querySelectorAll('a[href*="google.com/maps"]').forEach(a=>{try{const u=new URL(a.href);if(u.hostname!=='www.google.com'||!u.pathname.startsWith('/maps/'))return;const next=new URL(u);next.searchParams.set('travelmode',mode);if(next.href!==a.href)a.href=next.href}catch{}})};
const restoreRoute=()=>{const route=window.routeStops;if(!Array.isArray(route)||!Array.isArray(window.pandals))return;try{const saved=JSON.parse(storageGet('kolkata-pujo-route','[]'));if(!Array.isArray(saved)||!saved.length||route.length)return;const restored=saved.map(x=>x?.name).filter(Boolean).map(name=>window.pandals.find(p=>p.name===name)).filter(Boolean).slice(0,8);if(restored.length)route.push(...restored)}catch{}};
const persistRoute=()=>{const route=window.routeStops;if(Array.isArray(route))storageSet('kolkata-pujo-route',JSON.stringify(route.map(p=>({name:p?.name})).filter(p=>p.name)))};
const a11y=()=>{const menu=document.querySelector('.menu'),nav=document.querySelector('nav');if(menu){if(!menu.hasAttribute('aria-label'))menu.setAttribute('aria-label','Open navigation');if(nav?.id&&!menu.hasAttribute('aria-controls'))menu.setAttribute('aria-controls',nav.id);const expanded=nav?.dataset.open==='true'?'true':'false';if(menu.getAttribute('aria-expanded')!==expanded)menu.setAttribute('aria-expanded',expanded)}document.querySelectorAll('a[target="_blank"]').forEach(a=>{const rel=(a.getAttribute('rel')||'').split(/\s+/).filter(Boolean);if(!rel.includes('noopener')){rel.push('noopener');a.setAttribute('rel',rel.join(' '))}});document.querySelectorAll('img:not([alt])').forEach(img=>img.setAttribute('alt',''))};
const imageFallbacks=()=>document.querySelectorAll('img').forEach(img=>{if(img.dataset.qaFallback)return;img.dataset.qaFallback='1';img.addEventListener('error',()=>{img.style.display='none';img.closest('.pandal-card,.gallery-grid .tile')?.classList.add('image-unavailable')},{once:true})});
const mapResize=()=>{const map=window.map;if(map?.invalidateSize)requestAnimationFrame(()=>map.invalidateSize(false))};
let observer=null,running=false,scheduled=false;
const run=()=>{scheduled=false;if(running)return;running=true;observer?.disconnect();try{a11y();rewriteMapsLinks();imageFallbacks();restoreRoute();mapResize()}finally{running=false;if(observer)observer.observe(document.body,{childList:true,subtree:true})}};
const schedule=()=>{if(running||scheduled)return;scheduled=true;requestAnimationFrame(run)};
const init=()=>{run();setTimeout(run,1200);setTimeout(run,3000)};
document.addEventListener('click',e=>{if(e.target.closest('.mode-btn,.menu,.suite-add,.catalog-route,.remove-stop,#route-stops button,#suite-optimize'))setTimeout(schedule,0);const link=e.target.closest('a[href*="google.com/maps"]');if(link){try{const u=new URL(link.href);if(u.hostname==='www.google.com'&&u.pathname.startsWith('/maps/')){u.searchParams.set('travelmode',mapsMode());if(u.href!==link.href)link.href=u.href}}catch{}}},{capture:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const nav=document.querySelector('nav'),menu=document.querySelector('.menu');if(nav?.dataset.open==='true'){nav.dataset.open='false';nav.style.display='';menu?.setAttribute('aria-expanded','false')}}if(e.key==='Enter'){const card=e.target.closest?.('.pandal-card[tabindex]');if(card&&!e.target.closest('button,a'))card.click()}});
window.addEventListener('resize',mapResize);window.addEventListener('orientationchange',()=>setTimeout(mapResize,250));window.addEventListener('beforeunload',persistRoute);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
observer=new MutationObserver(schedule);if(document.body)observer.observe(document.body,{childList:true,subtree:true});
})();
