(()=>{
'use strict';
const currentMode=()=>window.KolkataState?.get?.().mode||'walking';
const pins=()=>window.KOLKATA_CANONICAL_PINS||{};
function loadSitePolish(){if(document.getElementById('site-polish-css'))return;const link=document.createElement('link');link.id='site-polish-css';link.rel='stylesheet';link.href='site-polish.css';document.head.appendChild(link)}
function syncMode(){document.querySelectorAll('.mode-btn').forEach(btn=>{if(btn.dataset.kolkataModeBound)return;btn.dataset.kolkataModeBound='1';btn.addEventListener('click',()=>{if(btn.dataset.mode)window.KolkataState?.update?.({mode:btn.dataset.mode})},{passive:true})});const saved=currentMode();const btn=document.querySelector(`.mode-btn[data-mode="${CSS.escape(saved)}"]`);if(btn&&!btn.classList.contains('active'))btn.click()}
function exposeSelector(){window.selectPandal=p=>{if(!p)return;const map=window.kolkataMap||window.map;if(map?.flyTo)map.flyTo([p.lat,p.lng],15,{duration:.7});if(map?.eachLayer)map.eachLayer(layer=>{if(layer?.options?.title===p.name&&layer.openPopup)layer.openPopup()});document.querySelectorAll('.pandal-card').forEach(c=>c.classList.toggle('selected',c.dataset.name===p.name));document.querySelector(`.pandal-card[data-name="${CSS.escape(p.name)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}}
function patchCatalogCards(){const canonical=pins(),active=document.querySelector('.mode-btn.active')?.dataset.mode||currentMode(),mode=active==='two-wheeler'?'driving':active;document.querySelectorAll('#pandal-list .pandal-card[data-name]').forEach(card=>{const pin=canonical[card.dataset.name];if(!pin)return;const link=card.querySelector('.route');if(link)link.href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${pin[0]},${pin[1]}`)}&travelmode=${encodeURIComponent(mode)}`;const btn=card.querySelector('.catalog-map,.suite-map');if(btn){btn.disabled=false;btn.textContent='View map'}let status=card.querySelector('.pin-status');if(!status){status=document.createElement('div');status.className='pin-status';card.querySelector('h3')?.after(status)}status.classList.add('verified');status.classList.remove('pending');status.textContent='● Exact map pin verified'});document.querySelectorAll('[data-verified-count]').forEach(el=>el.textContent=String(Object.keys(canonical).length))}
function patchUndefinedDirections(){const active=document.querySelector('.mode-btn.active')?.dataset.mode||currentMode(),mode=active==='two-wheeler'?'driving':active;document.querySelectorAll('#pandal-list .pandal-card[data-name] a.route').forEach(link=>{if(!/google\.com\/maps\/dir\//i.test(link.href)||!/destination=(?:undefined|null)/i.test(link.href))return;const p=window.pandals?.find?.(item=>item.name===link.closest('.pandal-card')?.dataset.name);if(!p)return;if(Number.isFinite(p.lat)&&Number.isFinite(p.lng))link.href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${p.lat},${p.lng}`)}&travelmode=${encodeURIComponent(mode)}`;else link.href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name}, ${p.area||''}, Kolkata, West Bengal`)}`;link.target='_blank';link.rel='noopener'})}
function patchHolidayCopy(){document.querySelectorAll('.hero .eyebrow,.puja-countdown .countdown-title,.puja-countdown .countdown-date').forEach(el=>{if(el.classList.contains('countdown-title'))el.textContent=el.textContent.replace(/Durga Puja begins in/i,'Puja holiday window begins in');if(el.classList.contains('countdown-date'))el.textContent=el.textContent.replace(/Maha Chaturthi · 15 October 2026/i,'Holiday window · 15 October 2026');if(el.classList.contains('eyebrow'))el.textContent=el.textContent.replace(/PUJA 15—26 OCTOBER 2026/i,'HOLIDAY WINDOW 15—26 OCTOBER 2026')})}
function fixGalleryA11y(){document.querySelectorAll('.gallery-grid .tile').forEach((tile,i)=>{tile.setAttribute('role','button');tile.setAttribute('tabindex','0');tile.setAttribute('aria-label',tile.getAttribute('aria-label')||`Open gallery image ${i+1}`);if(tile.dataset.kolkataGalleryBound)return;tile.dataset.kolkataGalleryBound='1';tile.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tile.click()}})})}
function normalizeLinks(){const active=document.querySelector('.mode-btn.active')?.dataset.mode||currentMode(),mode=active==='two-wheeler'?'driving':active;document.querySelectorAll('a[href*="google.com/maps/dir/"]').forEach(a=>{try{const u=new URL(a.href);u.searchParams.set('travelmode',mode);a.href=u.toString();const rel=new Set((a.rel||'').split(/\s+/).filter(Boolean));rel.add('noopener');a.rel=[...rel].join(' ')}catch{}})}
function loadLeafletFallback(){if(window.L||document.getElementById('leaflet-fallback-script'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';css.id='leaflet-fallback-css';document.head.appendChild(css);const script=document.createElement('script');script.id='leaflet-fallback-script';script.src='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js';script.onload=()=>window.initKolkataMap?.();script.onerror=()=>{};document.head.appendChild(script)}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js',{scope:'./'}).catch(()=>{})}
function bootIntro(){if(sessionStorage.getItem('kolkata-intro-seen')==='1')return;const intro=document.createElement('div');intro.id='puja-intro';intro.className='puja-intro';intro.setAttribute('aria-label','কলকাতা দুর্গাপূজা ২০২৬ intro');intro.innerHTML='<div class="puja-intro-noise" aria-hidden="true"></div><div class="puja-intro-lamp" aria-hidden="true"><span></span></div><div class="puja-intro-content"><div class="puja-intro-kicker">KOLKATA · SHARODIYA 2026</div><div class="puja-intro-rule" aria-hidden="true"><i></i></div><div class="puja-intro-bengali">কলকাতা</div><div class="puja-intro-title">দুর্গাপূজা</div><div class="puja-intro-year">২০২৬</div><p class="puja-intro-tagline">Where the city becomes art.</p><button class="puja-intro-skip" type="button">Enter Kolkata <span>↗</span></button></div><div class="puja-intro-progress" aria-hidden="true"><span></span></div>';document.body.prepend(intro);document.documentElement.classList.add('puja-intro-active');const finish=()=>{if(intro.dataset.done)return;intro.dataset.done='1';sessionStorage.setItem('kolkata-intro-seen','1');document.documentElement.classList.remove('puja-intro-active');intro.classList.add('is-leaving');setTimeout(()=>intro.remove(),700)};intro.querySelector('.puja-intro-skip')?.addEventListener('click',finish,{once:true});if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setTimeout(finish,350)}else{setTimeout(finish,3200)}}
function patchAll(){patchCatalogCards();patchUndefinedDirections();patchHolidayCopy();fixGalleryA11y();normalizeLinks()}
function boot(){loadSitePolish();bootIntro();window.KOLKATA_NORMALIZE_PANDALS?.(window.pandals);syncMode();exposeSelector();if(!window.L)loadLeafletFallback();patchAll();registerSW();setTimeout(patchAll,1200);setTimeout(patchAll,3200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.addEventListener('load',patchAll,{once:true});
})();
