import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const server=spawn('python3',['-m','http.server','4173','--bind','127.0.0.1'],{stdio:'ignore'});const wait=ms=>new Promise(r=>setTimeout(r,ms));const fail=m=>{throw new Error(m)};let browser;
try{
 await wait(500);browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});const page=await context.newPage();const pageErrors=[];const failedRequests=[];page.on('pageerror',e=>pageErrors.push(e.message));page.on('requestfailed',r=>{if(r.url().startsWith('http://127.0.0.1:4173/'))failedRequests.push(`${r.method()} ${r.url()} :: ${r.failure()?.errorText||'failed'}`)});
 await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>document.querySelectorAll('.pandal-card').length>=109,null,{timeout:30000});await page.waitForFunction(()=>Object.keys(window.KOLKATA_CANONICAL_PINS||{}).length===36,null,{timeout:10000});await page.waitForFunction(()=>document.querySelectorAll('.leaflet-marker-icon').length===41,null,{timeout:30000});await wait(1000);
 const checks=await page.evaluate(()=>({cards:document.querySelectorAll('.pandal-card').length,canonicalPins:Object.keys(window.KOLKATA_CANONICAL_PINS||{}).length,pandals:Array.isArray(window.pandals)?window.pandals.length:-1,markerCount:document.querySelectorAll('.leaflet-marker-icon').length,leaflet:Boolean(window.L),map:Boolean(document.getElementById('pandal-map')?._leaflet_id),state:window.KolkataState?.get?.()||null,search:Boolean(document.getElementById('pandal-search')),route:Boolean(document.getElementById('route-stops')),menu:Boolean(document.querySelector('.menu')),toolkit:Boolean(document.querySelector('#puja-suite-launcher')),bingo:Boolean(document.querySelector('#puja-bingo')),guides:Boolean(document.querySelector('.puja-guides')),swSupported:'serviceWorker'in navigator,canonicalMatches:Object.entries(window.KOLKATA_CANONICAL_PINS||{}).every(([name,c])=>{const p=window.pandals?.find(x=>x.name===name);return p&&Number(p.lat)===Number(c[0])&&Number(p.lng)===Number(c[1])}),expandedPins:['Tala Park','Muhammad Ali Park','Dumdum Park Tarun Dal','Chorebagan Sarbojanin','Bakul Bagan'].every(name=>{const p=window.pandals?.find(x=>x.name===name);return p&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))})}));
 if(checks.cards!==109)fail(`Expected 109 pandal cards, found ${checks.cards}`);if(checks.canonicalPins!==36)fail(`Expected 36 canonical pins, found ${checks.canonicalPins}`);if(checks.pandals!==100)fail(`Expected unified window.pandals catalog to contain 100 entries, found ${checks.pandals}`);if(checks.markerCount!==41)fail(`Expected 41 Leaflet markers (36 canonical + 5 additional verified catalog pins), found ${checks.markerCount}`);if(!checks.canonicalMatches)fail('Canonical coordinates do not match the unified pandal catalog');if(!checks.expandedPins)fail('Verified expansion pins were not merged into the unified pandal catalog');if(!checks.leaflet||!checks.map)fail('Leaflet map did not initialize');if(!checks.search||!checks.route||!checks.menu)fail('Core mobile controls are missing');if(!checks.toolkit||!checks.bingo||!checks.guides)fail('One or more Puja feature modules did not load');if(!checks.state||checks.state.version!==3)fail('Unified v3 state store did not initialize');
 const search=page.locator('#pandal-search');await search.fill('20 Palli');await wait(250);if(await page.locator('.pandal-card:not(.v2-hidden)').count()<1)fail('Search did not find 20 Palli Sarbojani Durgotsab');if(!await page.locator('.pandal-card:not(.v2-hidden)').first().getAttribute('data-name').then(n=>n?.includes('20 Palli')))fail('20 Palli search result was not the expected pandal');await search.fill('');await wait(250);
 const extraSearch=page.locator('#pandal-search');await extraSearch.fill('Chaltabagan Sarbojanin');await wait(250);if(await page.locator('[data-extra-pandal="true"]').count()!==1)fail('Expanded discovery listing was not injected');await extraSearch.fill('');await wait(250);
 const firstCard=page.locator('.pandal-card').filter({hasText:'Bagbazar Sarbojanin'}).first();const add=firstCard.locator('.catalog-route,.add-route').first();if(await add.count()!==1)fail('No route control found for Bagbazar Sarbojanin');await add.click();await wait(200);if((await page.locator('#route-count').textContent())?.trim()!=='1 / 8')fail('Adding a pandal did not update the route count');const directionHref=await firstCard.locator('a.route').getAttribute('href');if(!directionHref?.match(/(?:destination=|query=)[^&]+/))fail('Directions URL is missing a destination/query');
 const drive=page.locator('.mode-btn[data-mode="driving"]');await drive.click();await page.waitForFunction(()=>window.KolkataState?.get?.().mode==='driving',null,{timeout:3000});await page.waitForFunction(()=>document.querySelector('#open-route')?.href.includes('travelmode=driving'),null,{timeout:3000});
 await firstCard.locator('h3').click();await page.waitForFunction(()=>document.querySelector('#pandal-details')?.hidden===false,null,{timeout:5000});if(!await page.locator('#details-title').textContent().then(t=>t?.includes('Bagbazar Sarbojanin')))fail('Pandal details modal opened with the wrong record');await wait(250);if(await page.locator('#pp-mark').count()!==1||await page.locator('#pp-note').count()!==1)fail('Personal notebook controls did not attach to the details modal');await page.locator('#pp-mark').click();await wait(100);if(!(await page.evaluate(()=>window.KolkataState.get().visited)).includes('Bagbazar Sarbojanin'))fail('Visited state was not saved in the unified store');await page.locator('#pp-note').fill('Smoke-test note');if(await page.locator('#pp-note').inputValue()!=='Smoke-test note')fail('Private note field did not accept input');await page.locator('#pandal-details .pandal-details-close').click();
 const fav=firstCard.locator('.v2-fav').first();if(await fav.count()!==1)fail('Favourite control was not attached to the pandal card');await fav.click();await wait(100);if(!(await page.evaluate(()=>window.KolkataState.get().saved)).includes('Bagbazar Sarbojanin'))fail('Favourite state was not saved in the unified store');
 const bingoCell=page.locator('#puja-bingo .bingo-cell').first();if(await bingoCell.count()!==1)fail('Puja Bingo board is missing');await bingoCell.click();await wait(100);if(!(await page.evaluate(()=>window.KolkataState.get().bingo)).includes(0))fail('Puja Bingo state was not saved in the unified store');
 await page.locator('#puja-suite-launcher').click();await page.waitForSelector('#puja-suite-panel[open]',{timeout:3000});await page.locator('#puja-suite-panel [data-close]').click();await page.locator('#clear-route').click();await wait(100);if((await page.locator('#route-count').textContent())?.trim()!=='0 / 8')fail('Clear route did not empty the planner');const after=await page.evaluate(()=>window.KolkataState.get());if(after.route.length||after.completed.length)fail('Route state was not cleared in the unified store');
 const menu=page.locator('.menu');await menu.click();if(await menu.getAttribute('aria-expanded')!=='true')fail('Mobile menu did not open');await menu.click();if(await menu.getAttribute('aria-expanded')!=='false')fail('Mobile menu did not close');if(checks.swSupported)await page.waitForFunction(async()=>Boolean(await navigator.serviceWorker.getRegistration()),null,{timeout:5000}).catch(()=>fail('Service worker did not register within the smoke-test window'));if(pageErrors.length)fail(`Runtime page errors: ${pageErrors.join(' | ')}`);if(failedRequests.length)fail(`Unexpected local asset request failures: ${failedRequests.join(' | ')}`);console.log('Production smoke test passed:',JSON.stringify(checks));
}finally{await browser?.close();server.kill('SIGTERM')}
